### ISSUE TITLE
Writing empties entire file with prettier-plugin-sh

### ISSUE THREAD

**Issue by carhartl** [rx-ts/sh-syntax#46]
After updating prettier-plugin-sh from 0.11.0 to 0.12.3 we see issues being reported in files that were ok so far, but when applying to fix, e.g. `npx prettier --write .` the reported files appear to be empty.

Noticed here: https://github.com/digitalservicebund/typescript-vite-application-template/pull/60

The repo is public so you should be able to try out.

**Comment by JounQin** [comment]
Thanks for sharing, I'll take a look when I'm free.

**Comment by JounQin** [comment]
Hi, I've decided to revert to use `mvdan-sh` for now, but at least we have more test cases for `sh-syntax`...

Please try `prettier-plugin-sh@0.12.4`.
